### ISSUE TITLE
Leap second inserted in June 2015

### ISSUE THREAD

**Issue by edgar-bonet** [jtauber/mars-clock#2]
In index.html, lines 254, 256 and 493, it is stated that

```
TT - UTC = (35 + 32.184) s
```

Actually, since 1 July 2015, it's (36 + 32.184) s.

**Comment by edgar-bonet** [comment]
And since 1 January 2017 it's (37 + 32.184) s.

**Comment by jtauber** [comment]
I'll accept a pull request if you (or anyone else) wants to put one together.

**Comment by edgar-bonet** [comment]
I just filed pull request #5. Since the current TAI−UTC offset is time-sensitive information, I put it in a single place, at the top of the file. This makes it easier to update whenever a new leap second is inserted.

**Comment by jtauber** [comment]
Perfect, thanks!
